### PR TITLE
Extend JwtHeader to allow additional fields

### LINKED ISSUE #475: Types for JWT header do not accept additional arbitrary fields
**Problem**
[createSigner](https://github.com/nearform/fast-jwt/blob/master/src/signer.js#L191) correctly accepts additional arbitrary fields to the header.
However the [interface for the JwtHeader ](https://github.com/nearform/fast-jwt/blob/master/src/index.d.ts#L83) doesn't.

**Example**
```
import { createSigner } from "fast-jwt";

const signer = createSigner({
	key: "secret",
	algorithm: "HS256",
	header: { custom: "header" },
});

// ts error:
1. No overload matches this call.
     Overload 1 of 2, '(options?: Partial<SignerOptions & { key: any; }> | undefined): (payload: any) => string', gave the following error.
       Type '{ custom: string; }' is not assignable to type 'JwtHeader'.
         Object literal may only specify known properties, and 'custom' does not exist in type 'JwtHeader'. [2769]

```
**Current workaround**
I can use //@ts-ignore to force TS to like the additional field.

**Proposed solution**
We can add a generic type to `JwtHeader`
I would be happy to submit a PR in case

### PR DESCRIPTION
**Pull request by Akallabet**
Fixes #475 
Extends JwtHeader interface to allow additional fields

### CODE REVIEW

File: src/index.d.ts [hunk 1]
```diff
@@ -63,8 +63,8 @@ type SignerCallback = (e: Error | TokenError | null, token: string) => void
 type VerifierCallback = (e: Error | TokenError | null, payload: any) => void
 
 type DecodedJwt = {
-  header: { [key: string]: any },
-  payload: any,
+  header: { [key: string]: any }
```
Comment (ilteoood) [inline src/index.d.ts:66]: This can be the occasion to change this to a Record

File: src/index.d.ts [hunk 2]
```diff
@@ -80,7 +80,7 @@ declare function VerifierSync(token: string | Buffer): any
 declare function VerifierAsync(token: string | Buffer): Promise<any>
 declare function VerifierAsync(token: string | Buffer, cb: object): void
 
-export interface JwtHeader {
+export interface JwtHeader extends Record<string, any> {
```
Comment (ilteoood) [inline src/index.d.ts:83]: Did you check if this still gives code hints?

Comment (Akallabet) [reply src/index.d.ts:83]: Yes it still does!

**Review by ilteoood — APPROVED** [review]

**Review by simoneb — APPROVED** [review]
